config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match "/404", as: "not_found", to: "errors_pages#not_found", via: :all
  match "/422", as: "unprocessable_entity", to: "errors_pages#internal_server_error", via: :all
  match "/500", as: "internal_error", to: "errors_pages#internal_server_error", via: :all
  get "/sitemap.xml", to: redirect("https://20aubac.s3.eu-west-3.amazonaws.com/sitemap.xml")

  devise_for :users,
    path: "compte",
    skip: [:passwords],
    path_names: {
      sign_in: "acceder",
      sign_out: "deconnecter",
      sign_up: "creer",
      edit: "editer"
    },
    controllers: {registrations: "registrations"}

  authenticate :user, ->(u) { u.admin? } do
    mount ActiveAnalytics::Engine, at: "analytics" # http://localhost:3000/analytics
  end

  devise_scope :user do
    match "/compte/recuperer" => "devise/passwords#create", :as => :user_password, :via => [:post]
    match "/compte/recuperer" => "devise/passwords#update", :via => %i[put patch]
    get "compte/recuperer", to: "devise/passwords#new", as: :new_user_password
    get "mdp/editer", to: "devise/passwords#edit", as: :edit_user_password
  end

  post "acces-premium/abonnement-stripe", to: "premium_accesses#create_stripe_subscription"
  post "acces-premium/notification-stripe", to: "premium_accesses#webhook_stripe"
  put "acces-premium/:id/annuler", to: "premium_accesses#cancel"
  put "acces-premium/:id/activer", to: "premium_accesses#activate"

  root "static_pages#home"
  get "apropos-presentation", to: "static_pages#about_whatwedo"
  get "apropos-publication", to: "static_pages#about_berewarded"
  get "apropos-premium", to: "static_pages#about_premiumaccess"
  get "apropos-mentions", to: "static_pages#about_legalstatement"
  get "apropos-partenaires", to: "static_pages#about_partners"
  get "plan-site", to: "static_pages#site_plan"

  get "membres-accueil", to: "users_pages#home"
  get "membres-corriges", to: "users_pages#essays"
  get "membres-accespremium", to: "users_pages#premium_accesses"
  get "membres-premiumabonnement", to: "users_pages#premium_recurring"

  get "admin-corriges", to: "admin_pages#essays"
  get "admin-corriges-externes", to: "admin_pages#external_essays"
  get "admin-plans", to: "admin_pages#plans"
  get "admin-audios", to: "admin_pages#audios"
  get "admin-titres", to: "admin_pages#titles"
  get "admin-sujets", to: "admin_pages#topics"
  get "admin-categories-incompletes", to: "admin_pages#categories_missing_info"
  get "admin-influences", to: "admin_pages#influences"
  get "admin-categories-orphelines", to: "admin_pages#orphan_categories"
  get "admin-professeurs", to: "admin_pages#professors"
  get "admin-statistiques", to: "admin_pages#statistics"

  get "corriges-populaires", to: "essays#most_popular"
  get "corriges-recents", to: "essays#recently_updated"

  get "recherche", to: "topics#search"

  namespace :essay_contents, path: "" do
    resources :internals, path: "corriges", except: %i[index] do
      put "publish", on: :member
      put "validate", on: :member
      put "premiumize", on: :member
      put "update_topic", on: :member
    end

    resources :externals, path: "corriges-externes", only: %i[show destroy] do
      put "archive", on: :member
      get "archive-html", on: :member
      get "archive-pdf", on: :member
    end
  end

  namespace :quiz do
    resource :answers, path: "", only: %i[show new create]
  end

  get "categories/karl-popper/sujets", to: redirect("/categories/popper/sujets")
  get "categories/pierre-duhem/sujets", to: redirect("/categories/duhem/sujets")
  get "categories/alain-badiou/sujets", to: redirect("/categories/badiou/sujets")
  get "categories/rousseau/sujets", to: redirect("/categories/rousseau-philo/sujets")
  get "categories/jean-jacques-rousseau/sujets", to: redirect("/categories/rousseau-francais/sujets")
  get "categories/jean-paul-sartre/sujets", to: redirect("/categories/sartre-philo/sujets")
  get "categories/sartre/sujets", to: redirect("/categories/sartre-francais/sujets")
  get "categories/diderot/sujets", to: redirect("/categories/diderot-philo/sujets")
  get "categories/denis-diderot/sujets", to: redirect("/categories/diderot-francais/sujets")
  get "categories/montesquieu/sujets", to: redirect("/categories/montesquieu-philo/sujets")
  get "categories/charles-louis-montesquieu/sujets", to: redirect("/categories/montesquieu-francais/sujets")
  get "categories/russel/sujets", to: redirect("/categories/russell/sujets")

  get "categories/devoir-respect/sujets", to: redirect("/categories/devoir/sujets")
  get "categories/histoire/sujets", to: redirect("/categories/temps/sujets")
  get "categories/justice-droit/sujets", to: redirect("/categories/justice/sujets")
  get "categories/existence-temps/sujets", to: redirect("/categories/temps/sujets")
  get "categories/travail-technique/sujets", to: redirect("/categories/travail/sujets")
  get "categories/societe/sujets", to: redirect("/categories/etat/sujets")
  get "categories/desir/sujets", to: redirect("/categories/bonheur/sujets")
  get "categories/perception/sujets", to: redirect("/categories/conscience/sujets")
  get "categories/autrui/sujets", to: redirect("/categories/conscience/sujets")
  get "categories/theorie-experience/sujets", to: redirect("/categories/science/sujets")
  get "categories/demonstration-logique/sujets", to: redirect("/categories/raison/sujets")
  get "categories/matiere-esprit/sujets", to: redirect("/categories/conscience/sujets")
  get "categories/interpretation/sujets", to: redirect("/categories/conscience/sujets")
  get "categories/philosophie/sujets", to: redirect("/categories/verite/sujets")

  resources :categories, only: %i[index edit update destroy] do
    get "/:matiere-:type", action: :index, on: :collection, as: "params"
    resources :topics, path: "sujets", only: %i[index] do
      get "/:page", action: :index, on: :collection, as: "params"
    end
  end

  resources :topics, path: "sujets", except: %i[index show] do
    get "/:matiere-:type", action: :index_all, on: :collection, as: "params"
  end

  get "francais/commentaires-composes.html", to: redirect("/categories/francais-commentaire")
  get "philo/corriges-dissertation-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "philo/corriges-commentaire-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "francais/commentaires-composes-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "philo/corriges-:type.html", to: redirect("/categories/philosophie-%{type}")
  get "plan-site.html", to: redirect("/plan-site")
  get "apropos-presentation.html", to: redirect("/apropos-presentation")
  get "apropos-contribuez.html", to: redirect("/apropos-publication")
  get "apropos-mentions.html", to: redirect("/apropos-mentions")
  get "recherche.html", to: redirect("/recherche")
  get "compte-creer.html", to: redirect("/compte/creer")
  get "compte-acceder.html", to: redirect("/compte/acceder")
  get "compte-recuperer.html", to: redirect("/compte/recuperer")
  get "aide-cgu.html", to: redirect("/aide-cgu")
  get "francais/commentaires-composes.html", to: redirect("/categories/francais-commentaire")
  get "philo/corriges-dissertation-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "philo/corriges-commentaire-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "francais/commentaires-composes-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "philo/corriges-:type.html", to: redirect("/categories/philosophie-%{type}")
  # TO BE REMOVED: force redirection for legacy urls containing  "-r" in keywords
  get "philo/dissertation-15-dire-autrui-semblable-dire-ressemble-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-16-rapports-autres-necessairement-ordre-conflit-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-53-avoir-raison-contre-autres-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-58-religion-liberte-excluent-elles-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-73-preferer-revolte-resignation-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-79-epictete-entretiens-role-philosophie-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-85-recherche-bonheur-necessairement-immorale-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-88-raison-oppose-toutes-formes-croyance-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-98-usage-raison-garantie-contre-illusion-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-106-accomplir-tous-desirs-bonne-regle-vie-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-124-descartes-lettre-a-elisabeth-rapport-entre-bonheur-chance-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-137-platon-gorgias-457d-458a-il-y-a-plus-grand-avantage-a-etre-refute-que-refuter-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-140-nietzsche-par-dela-bien-mal-role-philosophe-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-148-kant-critique-raison-pratique-loi-morale-liberte-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-157-freud-repression-desirs-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-194-que-veut-dire-se-rendre-maitre-ses-passions-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-204-est-il-raisonnable-aimer-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-208-obeir-est-ce-renoncer-liberte-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-228-religion-nourrit-elle-amour-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-265-travailler-rend-il-libre-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-273-rousseau-contrat-social-passage-etat-nature-etat-civil-r:id.html", to: redirect("/corriges/%{id}")

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home
    @published_essays_count = Essay.published.count
    @last_modified_essays = Essay.top_by(:updated_at)
    @most_popular_essays = Essay.top_by(:hits_nb_last30d)
  end

  def about_whatwedo
  end

  def about_berewarded
  end

  def about_premiumaccess
  end

  def about_legalstatement
  end

  def about_partners
  end

  def site_plan
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about_berewarded.html.erb
<% content_for :page_title, 'Publiez vos corrigés' %>
<% content_for :h1_title, 'Publiez vos corrigés' %>
<% content_for :page_description, "Apprenez comment contribuer au contenu de 20aubac, et gagner un accès premium." %>
<% content_for :canonical_url, apropos_publication_url %>

<div class="content">
  <h1><%= yield(:h1_title) %></h1>

  <p>Participez aux contenus de 20aubac, et gagnez un accès aux contenus premium.</p>

  <h2 class="mt-4">Gagnez un accès premium pour chaque publication validée</h2>

  <p>En partageant une copie d'élève ou un commentaire personnel, vous aidez à votre tour d'autres élèves.</p>

  <p>Pour vous remercier de votre contribution, une fois celle-ci relue et validée, vous aurez un accès offert aux contenus premium pendant 30 jours pour chaque corrigé validé.</p>

  <h2 class="mt-4">Les étapes pour gagner un accès premium</h2>

  <p>Pour obtenir un accès premium offert de 30 jours, vous devez :
    <ul class="list-inside list-square">
      <li>Vous créer un compte</li>
      <li>Ajouter un corrigé personnel (non copié d'internet), complet et bien rédigé</li>
      <li>Une fois celui-ci proposé pour validation, attendre qu'il soit relu et validé manuellement</li>
    <ul>
  </p>

  <p>
    <%=
      path = current_user ?  new_essay_contents_internal_path : new_user_registration_path(suite: 'corrige')
      link_to('Proposer un corrigé', path, { class: 'button button-blue' })
    %>
  </p>

  <p class="mt-4">
    Vous pouvez également obtenir un accès immédiat, <%= link_to('en vous abonnant', apropos_premium_path) %>.
  </p>
</div>

app/views/static_pages/about_partners.html.erb
<% content_for :page_title, 'Partenaires de 20aubac' %>
<% content_for :h1_title, 'Partenaires de 20aubac' %>
<% content_for :page_description, 'Présentation des partenaires de 20aubac.' %>
<% content_for :canonical_url, apropos_partenaires_url %>

<div class="content">
  <h1><%= link_to(yield(:h1_title), yield(:canonical_url)) %></h1>

  <p class="mt-8">
    Les sites suivants ont accepté d'être partenaires de 20aubac, et nous les en remercions.
  </p>

  <div class="w-full mt-14 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10 justify-items-center">
    <div class="text-center">
      <figure>
        <%= link_to('https://fr.jooble.org/') do %>
          <%= image_tag('partners_jooble.png', alt: "Jooble, offres d'emploi partout en France", class: 'inline-block') %>
        <% end %>
        <figcaption>
          <%= link_to("Jooble, offres d'emploi partout en France", 'https://fr.jooble.org', class: 'mt-2 inline-block') %>
        </figcaption>
      </figure>
    </div>

    <div class="text-center">
      <figure>
        <%= link_to('https://www.mediaclasse.fr') do %>
          <%= image_tag('partners_mediaclasse.png', alt: 'Mediaclasse, La littérature analysée en vidéo', class: 'inline-block') %>
        <% end %>
        <figcaption>
          <%= link_to('Mediaclasse, La littérature analysée en vidéo', 'https://www.mediaclasse.fr', class: 'mt-2 inline-block') %>
        </figcaption>
      </figure>
    </div>

    <div class="w-full text-center">
      <figure>
        <div class="flex items-center w-full text-center border-8 border-gray-900 border-dotted h-229px">
            <%= link_to(apropos_mentions_path, class:'no-underline inline-block mx-auto') do %>
              <span class="text-9xl">+</span>
            <% end %>
          </div>
        <figcaption>
          <%= link_to('Votre site ici', apropos_mentions_path, class: 'mt-2 inline-block') %>
        </figcaption>
      </figure>
    </div>
</div>
</div>

app/views/static_pages/about_premiumaccess.erb
<% content_for :page_title, 'Accès premium' %>
<% content_for :h1_title, 'Prenez du niveau en français et en philo' %>
<% content_for :page_description, "Qu'est-ce que les contenus premium, que contiennent-ils, que permettent-ils et comment y accéder." %>
<% content_for :canonical_url, apropos_premium_url %>

<div class="content">
  <h1><%= yield(:h1_title) %></h1>

  <p>
    Accédez sans limite à tous nos contenus exclusifs, relus et validés manuellement.
  </p>

  <h2 class="mt-4">Que contient l'accès premium ?</h2>

  <p>
    L'accès premium comprend les avantages suivants:
    <ul class="list-inside list-square">
      <li>L'accès à tous nos corrigés exclusifs</li>
      <li>L'accès à toutes nos archives, téléchargeables au format pdf</li>
      <li>L'assurance d'ajouts réguliers de nouveaux contenus</li>
    <ul>
  </p>

  <h2 class="mt-4">Comment obtenir un accès premium ?</h2>

  <p>
    Le moyen le plus simple d'obtenir un accès est par abonnement:
    <ul class="list-inside list-square">
      <li>En créant un compte gratuitement, en moins d'une minute</li>
      <li>Puis en souscrivant par carte bancaire, pour 5€/mois</li>
      <li>Vous pouvez annuler votre abonnement à tout moment, en un clic</li>
    </ul>
  </p>

  <p>
    <%=
      path = current_user ?  membres_premiumabonnement_path : new_user_registration_path(suite: 'premium')
      link_to('Obtenir un accès premium', path, { class: 'button button-blue' })
    %>
  </p>

  <p class="mt-4">
    Vous également obtenir un accès de 30 jours, <%= link_to('en proposant vous-même un corrigé', apropos_publication_path) %>.
  </p>
</div>

app/views/static_pages/about_subscription.erb
<% content_for :page_title, 'Accès premium %>
<% content_for :h1_title, 'Accédez aux contenus premium de 20aubac' %>
<% content_for :page_description, "Qu'est-ce que les contenus premium, que sont-ils, que permettent-ils et comment y accéder." %>
<% content_for :canonical_url, apropos_publication_url %>

<div class="content">
  <h1><%= yield(:h1_title) %></h1>

  <h2 class="mt-4">L'objectif: proposer un maximum de contenu de qualité</h2>

  <p>L'objectif de 20aubac est de couvrir un maximum de sujets afin de proposer l'aide la plus complète possible. La vraie exigence est que les corrigés ou commentaires soient suffisament développés et sérieux dans leur contenu pour aider les visiteurs du site, principalement des lycéens.</p>

  <h2 class="mt-4">Contribuez en corrigeant et en partageant</h2>

  <p>Vous pouvez également contribuez au site en indiquant des erreurs que contiendraient les corrigés proposés. Si nous les validons manuellement, il peut y avoir bien sûr y avoir des erreurs qui s'y glissent.</p>

  <p>Enfin, n'hésitez-pas à partager les corrigés ou l'adresse du site: sur les réseaux sociaux, blogs, sites persos ou forums, toute aide est grandement appréciée !</p>

  <h2 class="mt-4">Contribuez en proposant vos propres corrigés</h2>

  <p>Les corrigés du site vous ont aidé ? Vous pouvez soumettre à votre tour vos propres copies d'élève ou commentaires personnels depuis un compte élève et partager ainsi vos travaux, qui seront relus et validés individuellement. De même si vous êtes professeur, vous pouvez obtenir le statut professeur et vos corrigés seront dès lors mieux mis en avant.</p>

  <p>Aussi vous restez à tout moment maître de vos contributions et pouvez modifier/supprimer vos contenus si vous le souhaitez.</p>

  <div class="max-w-md mx-auto mt-3 grid grid-cols-2 gap-2">
    <%= link_to(new_essay_contents_internal_path, class: "no-underline") do %>
      <div class="block button button-blue">Ajouter un corrigé</div>
    <% end %>
    <%= link_to(membres_premiumabonnement_path, class: "no-underline") do %>
      <div class="block button button-blue">Accès payant</div>
    <% end %>
  </div>
</div>

app/views/static_pages/about_whatwedo.html.erb
<% content_for :page_title, 'A propos de 20aubac' %>
<% content_for :h1_title, 'Présentation de 20aubac' %>
<% content_for :page_description, 'Présentation de 20aubac et de ses objectifs.' %>
<% content_for :canonical_url, apropos_presentation_url %>

<div class="content">
  <h1><%= link_to(yield(:h1_title), yield(:canonical_url)) %></h1>

  <h2 class="mt-4">Référencer le plus grand nombre de corrigés de qualité</h2>

  <p>20aubac se donne pour but de mettre à disposition des élèves le maximum de corrigés de qualité, pour réussir en français et en philosophie.</p>

  <h2 class="mt-4">L'exigence de qualité</h2>

  <p>20aubac se veut exigeant sur la qualité des corrigés publiés, et donner ainsi les clés aux élèves pour progresser avec tout ce que comporte une bonne copie : un développement clair, des arguments solides ou encore des références intéressantes et bien intégrées au raisonnement.</p>

  <p>20aubac se veut également exigeant sur la forme et l'application qui régit le contenu, avec des mises à jour et améliorations régulières pour une meilleure expérience, le tout sans publicité ni traceur.</p>

  <p>Pour soutenir l'amélioration continue du site et de ses contenus, certains corrigés sont <%= link_to('accessibles en accès premium', apropos_premium_path) %>.</p>

  <h2 class="mt-4">Une plate-forme d'échange de contenus</h2>

  <p>Pour s'assurer de l'ajout régulier de nouveaux contenus, le système de publication des corrigés permet aux élèves de partager leur propres copies et corrigés.</p>

  <p>Chaque soumission de copie d'élève est modérée pour s'assurer de la qualité du contenu soumis. Cela permet également d'éviter le plagiat de contenus publiés sur d'autres sites internet.</p>

  <p>Pour encourager la soumission de corrigés, chaque validation est <%= link_to("recompensée d'un accès premium offert", apropos_publication_path) %> pendant 30 jours.</p>
</div>

app/views/static_pages/home.html.erb
<% content_for :page_title, 'Dissertations et commentaires corrigés, bac de français et philo' %>
<% content_for :h1_title, 'Trouvez votre corrigé, en français ou en philo' %>
<% content_for :page_description, 'Dissertations et commentaires corrigés, en français et philosopie, pour préparer son oral de français et son bac de philo aux épreuves anticipées.' %>
<% content_for :canonical_url, root_url %>
<% content_for :ld_json do %>
  {
    "@context": "http://schema.org",
    "@type": "WebSite",
	  "url": "https://www.20aubac.fr/",
	  "potentialAction": {
      "@type": "SearchAction",
      "target": "https://www.20aubac.fr/recherche?q={search_term_string}",
      "query-input": "required name=search_term_string"
    }
  }
<% end %>
<div class="p-4 lg:p-0">
  <section id="imageindex" class="max-w-full mx-auto bg-center bg-no-repeat bg-cover border-2 border-gray-300 border-solid m-500 bg-students">
    <h1 class="inline-block px-2 py-0 ml-4 font-sans text-4xl font-bold bg-gray-400 bg-repeat md:ml-28 lg:ml-32 mt-136 md:mt-88 lg:mt-76 bg-opacity-85 text-shadow-index"><%= yield(:h1_title) %></h1>
    <div class="inline-block px-2 mt-2 mb-32 ml-4 font-sans text-3xl font-bold text-gray-200 bg-gray-700 bg-repeat md:ml-28 lg:ml-32 ">Parmi <%= @published_essays_count %> dissertations et commentaires validés manuellement</div>
  </section>
  <br />
  <section class="grid grid-cols-1 md:grid-cols-2 gap-3">
    <div class="flex flex-col">
      <div class="border-orange-600 box-index">
        <div>
          <h2 class="text-orange-600 h2-index"># Les derniers corrigés ajoutés ou mis à jour</h2>
        </div>
        <div>
          <ul>
            <% @last_modified_essays.each do |essay| %>
              <li class="list-outside ml-4 mr-6 list-square"><%= link_to(essay.topic.title_short.presence || essay.topic.title, essay.essay_content) %></li>
            <% end %>
          </ul>
        </div>

        <div class="mt-6">
          <%= link_to('Voir plus de corrigés ajoutés ou mis à jour', corriges_recents_path) %>
        </div>
      </div>
      <div>
        <%= link_to('Accédez aux commentaires de français', params_categories_path(type: "commentaire", matiere: "francais"), { class: "button-index button-orange" } ) %>
      </div>
    </div>

    <div class="flex flex-col">
      <div class="border-green-600 box-index">
        <div>
          <h2 class="text-green-600 h2-index"># Les corrigés les plus populaires</h2>
        </div>
        <div>
          <ul>
            <% @most_popular_essays.each do |essay| %>
              <li class="list-outside ml-4 mr-6 list-square"><%= link_to(essay.topic.title_short.presence || essay.topic.title, essay.essay_content) %></li>
            <% end %>
          </ul>
        </div>

        <div class="mt-6">
          <%= link_to('Voir plus de corrigés populaires', corriges_populaires_path) %>
        </div>
      </div>
      <div>
        <%= link_to('Accédez aux dissertations de philosophie', params_categories_path(type: "dissertation", matiere: "philosophie"), { class: "button-index button-green" } ) %>
      </div>
    </div>
  </section>
  <br />
  <section class="p-4 bg-gray-200">
    <h2 class="h2-index text-salmon">Des corrigés de qualité, en français et en philosophie</h2>

    <p>20aubac vous propose des corrigés de français (<%= link_to('commentaires', params_categories_path(type: "commentaire", matiere: "francais"), class: '') %>) et de philosophie (<%= link_to('dissertations', params_categories_path(type: "dissertation", matiere: "philosophie"), class: '') %> ou <%= link_to('commentaires', params_categories_path(type: "commentaire", matiere: "philosophie"), class: '') %>), de professeurs ou d'élèves, relus et validés manuellement.</p>

    <p>Conformément aux programmes du bac de français, les auteurs les plus étudiés sont présents: <%= link_to('Molière', category_topics_path(category_id: 'moliere')) %>, <%= link_to('Rousseau', category_topics_path(category_id: 'rousseau-francais')) %> ou encore <%= link_to('Apollinaire', category_topics_path(category_id: 'apollinaire')) %>. Nous proposons également en philosophie des dissertations en lien avec les notions officielles telles que <%= link_to('le désir', category_topics_path(category_id: 'desir')) %>, <%= link_to('le langage', category_topics_path(category_id: 'langage')) %> ou <%= link_to('la justice', category_topics_path(category_id: 'justice-droit')) %>. Les commentaires de philosophie traitent eux des textes des grands auteurs: <%= link_to('Descartes', category_topics_path(category_id: 'descartes')) %>, <%= link_to('Kant', category_topics_path(category_id: 'kant')) %> ou encore <%= link_to('Alain', category_topics_path(category_id: 'alain')) %>.</p>

    <p>Vous pouvez retrouver l'ensemble des sujets proposés en une page pour les <%= link_to('commentaires de français', params_topics_path(matiere: 'francais', type: 'commentaire')) %>, les <%= link_to('dissertations de philosophie', params_topics_path(matiere: 'philosophie', type: 'dissertation')) %> et les <%= link_to('commentaires de philosophie', params_topics_path(matiere: 'philosophie', type: 'commentaire')) %>.</p>

    <p><%= link_to('En savoir plus sur 20aubac',  apropos_presentation_path) %>.</p>
  </section>
</div>

app/views/static_pages/site_plan.html.erb
<% content_for :page_title, 'Plan de 20aubac' %>
<% content_for :h1_title, 'Plan du site' %>
<% content_for :page_description, 'Page répertoriant tout le contenu de 20aubac' %>
<% content_for :canonical_url, plan_site_url %>

<div class="content">
  <h1><%= link_to(yield(:h1_title), yield(:canonical_url)) %></h1>

  <%= render("shared/site_links") %>
</div>