config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match "/404", as: "not_found", to: "errors_pages#not_found", via: :all
  match "/422", as: "unprocessable_entity", to: "errors_pages#internal_server_error", via: :all
  match "/500", as: "internal_error", to: "errors_pages#internal_server_error", via: :all
  get "/sitemap.xml", to: redirect("https://20aubac.s3.eu-west-3.amazonaws.com/sitemap.xml")

  devise_for :users,
    path: "compte",
    skip: [:passwords],
    path_names: {
      sign_in: "acceder",
      sign_out: "deconnecter",
      sign_up: "creer",
      edit: "editer"
    },
    controllers: {registrations: "registrations"}

  authenticate :user, ->(u) { u.admin? } do
    mount ActiveAnalytics::Engine, at: "analytics" # http://localhost:3000/analytics
  end

  devise_scope :user do
    match "/compte/recuperer" => "devise/passwords#create", :as => :user_password, :via => [:post]
    match "/compte/recuperer" => "devise/passwords#update", :via => %i[put patch]
    get "compte/recuperer", to: "devise/passwords#new", as: :new_user_password
    get "mdp/editer", to: "devise/passwords#edit", as: :edit_user_password
  end

  post "acces-premium/abonnement-stripe", to: "premium_accesses#create_stripe_subscription"
  post "acces-premium/notification-stripe", to: "premium_accesses#webhook_stripe"
  put "acces-premium/:id/annuler", to: "premium_accesses#cancel"
  put "acces-premium/:id/activer", to: "premium_accesses#activate"

  root "static_pages#home"
  get "apropos-presentation", to: "static_pages#about_whatwedo"
  get "apropos-publication", to: "static_pages#about_berewarded"
  get "apropos-premium", to: "static_pages#about_premiumaccess"
  get "apropos-mentions", to: "static_pages#about_legalstatement"
  get "apropos-partenaires", to: "static_pages#about_partners"
  get "plan-site", to: "static_pages#site_plan"

  get "membres-accueil", to: "users_pages#home"
  get "membres-corriges", to: "users_pages#essays"
  get "membres-accespremium", to: "users_pages#premium_accesses"
  get "membres-premiumabonnement", to: "users_pages#premium_recurring"

  get "admin-corriges", to: "admin_pages#essays"
  get "admin-corriges-externes", to: "admin_pages#external_essays"
  get "admin-plans", to: "admin_pages#plans"
  get "admin-audios", to: "admin_pages#audios"
  get "admin-titres", to: "admin_pages#titles"
  get "admin-sujets", to: "admin_pages#topics"
  get "admin-categories-incompletes", to: "admin_pages#categories_missing_info"
  get "admin-influences", to: "admin_pages#influences"
  get "admin-categories-orphelines", to: "admin_pages#orphan_categories"
  get "admin-professeurs", to: "admin_pages#professors"
  get "admin-statistiques", to: "admin_pages#statistics"

  get "corriges-populaires", to: "essays#most_popular"
  get "corriges-recents", to: "essays#recently_updated"

  get "recherche", to: "topics#search"

  namespace :essay_contents, path: "" do
    resources :internals, path: "corriges", except: %i[index] do
      put "publish", on: :member
      put "validate", on: :member
      put "premiumize", on: :member
      put "update_topic", on: :member
    end

    resources :externals, path: "corriges-externes", only: %i[show destroy] do
      put "archive", on: :member
      get "archive-html", on: :member
      get "archive-pdf", on: :member
    end
  end

  namespace :quiz do
    resource :answers, path: "", only: %i[show new create]
  end

  get "categories/karl-popper/sujets", to: redirect("/categories/popper/sujets")
  get "categories/pierre-duhem/sujets", to: redirect("/categories/duhem/sujets")
  get "categories/alain-badiou/sujets", to: redirect("/categories/badiou/sujets")
  get "categories/rousseau/sujets", to: redirect("/categories/rousseau-philo/sujets")
  get "categories/jean-jacques-rousseau/sujets", to: redirect("/categories/rousseau-francais/sujets")
  get "categories/jean-paul-sartre/sujets", to: redirect("/categories/sartre-philo/sujets")
  get "categories/sartre/sujets", to: redirect("/categories/sartre-francais/sujets")
  get "categories/diderot/sujets", to: redirect("/categories/diderot-philo/sujets")
  get "categories/denis-diderot/sujets", to: redirect("/categories/diderot-francais/sujets")
  get "categories/montesquieu/sujets", to: redirect("/categories/montesquieu-philo/sujets")
  get "categories/charles-louis-montesquieu/sujets", to: redirect("/categories/montesquieu-francais/sujets")
  get "categories/russel/sujets", to: redirect("/categories/russell/sujets")

  get "categories/devoir-respect/sujets", to: redirect("/categories/devoir/sujets")
  get "categories/histoire/sujets", to: redirect("/categories/temps/sujets")
  get "categories/justice-droit/sujets", to: redirect("/categories/justice/sujets")
  get "categories/existence-temps/sujets", to: redirect("/categories/temps/sujets")
  get "categories/travail-technique/sujets", to: redirect("/categories/travail/sujets")
  get "categories/societe/sujets", to: redirect("/categories/etat/sujets")
  get "categories/desir/sujets", to: redirect("/categories/bonheur/sujets")
  get "categories/perception/sujets", to: redirect("/categories/conscience/sujets")
  get "categories/autrui/sujets", to: redirect("/categories/conscience/sujets")
  get "categories/theorie-experience/sujets", to: redirect("/categories/science/sujets")
  get "categories/demonstration-logique/sujets", to: redirect("/categories/raison/sujets")
  get "categories/matiere-esprit/sujets", to: redirect("/categories/conscience/sujets")
  get "categories/interpretation/sujets", to: redirect("/categories/conscience/sujets")
  get "categories/philosophie/sujets", to: redirect("/categories/verite/sujets")

  resources :categories, only: %i[index edit update destroy] do
    get "/:matiere-:type", action: :index, on: :collection, as: "params"
    resources :topics, path: "sujets", only: %i[index] do
      get "/:page", action: :index, on: :collection, as: "params"
    end
  end

  resources :topics, path: "sujets", except: %i[index show] do
    get "/:matiere-:type", action: :index_all, on: :collection, as: "params"
  end

  get "francais/commentaires-composes.html", to: redirect("/categories/francais-commentaire")
  get "philo/corriges-dissertation-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "philo/corriges-commentaire-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "francais/commentaires-composes-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "philo/corriges-:type.html", to: redirect("/categories/philosophie-%{type}")
  get "plan-site.html", to: redirect("/plan-site")
  get "apropos-presentation.html", to: redirect("/apropos-presentation")
  get "apropos-contribuez.html", to: redirect("/apropos-publication")
  get "apropos-mentions.html", to: redirect("/apropos-mentions")
  get "recherche.html", to: redirect("/recherche")
  get "compte-creer.html", to: redirect("/compte/creer")
  get "compte-acceder.html", to: redirect("/compte/acceder")
  get "compte-recuperer.html", to: redirect("/compte/recuperer")
  get "aide-cgu.html", to: redirect("/aide-cgu")
  get "francais/commentaires-composes.html", to: redirect("/categories/francais-commentaire")
  get "philo/corriges-dissertation-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "philo/corriges-commentaire-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "francais/commentaires-composes-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "philo/corriges-:type.html", to: redirect("/categories/philosophie-%{type}")
  # TO BE REMOVED: force redirection for legacy urls containing  "-r" in keywords
  get "philo/dissertation-15-dire-autrui-semblable-dire-ressemble-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-16-rapports-autres-necessairement-ordre-conflit-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-53-avoir-raison-contre-autres-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-58-religion-liberte-excluent-elles-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-73-preferer-revolte-resignation-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-79-epictete-entretiens-role-philosophie-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-85-recherche-bonheur-necessairement-immorale-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-88-raison-oppose-toutes-formes-croyance-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-98-usage-raison-garantie-contre-illusion-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-106-accomplir-tous-desirs-bonne-regle-vie-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-124-descartes-lettre-a-elisabeth-rapport-entre-bonheur-chance-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-137-platon-gorgias-457d-458a-il-y-a-plus-grand-avantage-a-etre-refute-que-refuter-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-140-nietzsche-par-dela-bien-mal-role-philosophe-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-148-kant-critique-raison-pratique-loi-morale-liberte-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-157-freud-repression-desirs-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-194-que-veut-dire-se-rendre-maitre-ses-passions-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-204-est-il-raisonnable-aimer-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-208-obeir-est-ce-renoncer-liberte-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-228-religion-nourrit-elle-amour-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-265-travailler-rend-il-libre-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-273-rousseau-contrat-social-passage-etat-nature-etat-civil-r:id.html", to: redirect("/corriges/%{id}")

app/controllers/users_pages_controller.rb
# frozen_string_literal: true

class UsersPagesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_eleve, only: %i[premium_accesses premium_recurring]
  before_action :check_existing_premium_access, only: %i[premium_recurring]

  def home
    @number_of_pending_essays = Essay.includes(%i[topic essay_content])
      .validation_pending
      .count

    @number_of_essays_without_proper_plan = EssayContents::Internal.includes(:topic, :essay)
      .where(essay: {status: :published})
      .where("content NOT LIKE '%[tp]II.%'")
      .count

    @number_of_topics_with_long_titles = Topic.joins(:essays)
      .where(essays: {status: :published})
      .where("(length(topics.title) > #{Topic::LONG_TITLE_THRESHOLD}
              and length(topics.title_short) = 0)
              or length(topics.title_short) > #{Topic::LONG_TITLE_THRESHOLD}
             ")
      .distinct
      .count

    @number_of_topics_without_audios = Topic.displayable
      .joins(:essays)
      .where(essays: {essay_content_type: "EssayContents::Internal"})
      .where("studied_text IS NOT NULL and studied_text != ''")
      .without_attached_audio
      .count

    @number_of_orphan_topics = Topic.where.missing(:essays).count

    number_of_unassigned_categories = Category
      .joins([:group, {topics: :essays}])
      .where(essays: {status: :published})
      .where(group: {name: Group::NON_ASSIGNED})
      .count

    number_of_categories_without_avatars = Category
      .joins([:group])
      .where.not(group: {name: Group::NON_ASSIGNED})
      .without_attached_avatar
      .count

    number_of_categories_without_sorting_index = Category
      .joins([:group])
      .where.not(group: {name: Group::NON_ASSIGNED})
      .where(sorting_index: nil)
      .count

    @number_of_categories_missing_info = number_of_unassigned_categories +
      number_of_categories_without_avatars +
      number_of_categories_without_sorting_index

    @number_of_categories_needing_links = Category
      .select('categories.id,
         COUNT(DISTINCT influences.id),
         COUNT(DISTINCT influencing_authors_categories_join.id),
         topics.count
      ')
      .joins(topics: :essays)
      .left_joins(:influencees, :influencers)
      .where(essays: {status: Essay.statuses[:published]})
      .group("categories.id")
      .having("
          COUNT(DISTINCT influences.id) = 0 AND
          COUNT(DISTINCT influencing_authors_categories_join.id) = 0 AND
          topics.count < #{Topic::DISPLAY_ADDITIONAL_INFO_THRESHOLD}
      ")
      .to_a
      .size

    @number_of_orphan_categories = Category
      .joins(:group)
      .without_attached_avatar
      .where.not(group: {name: Group::NON_ASSIGNED})
      .where.missing(:topics)
      .count
  end

  def essays
    @not_published_essays = current_user
      .essay_contents_internals
      .includes([topic: {category: :group}])
      .not_published
    @published_essays = current_user
      .essay_contents_internals
      .includes([topic: {category: :group}])
      .published
  end

  def premium_accesses
    @active_premium_access = current_user.active_premium_access
    @other_premium_accesses = if @active_premium_access
      current_user.premium_accesses
        .where.not(id: @active_premium_access.id)
        .order(expire_at: :desc)
    else
      current_user.premium_accesses
        .order(expire_at: :desc)
    end
  end

  def premium_recurring
    if current_user.stripe_id.blank?
      begin
        stripe_customer = StripeHelper.create_customer(current_user)
        @customer_id = stripe_customer.id
        current_user.update(stripe_id: @customer_id)
      rescue Stripe::InvalidRequestError => e
        RorVsWild.record_error(e)
        alert_message = "Stripe n'a pas pu créer votre identifiant. Veuillez vérifier la \
                         validité de votre adresse email, puis réessayez."
        flash[:alert] = alert_message
        redirect_to membres_accueil_path
      end
    else
      @customer_id = current_user.stripe_id
    end
  end

  private

  def check_existing_premium_access
    return unless current_user.active_premium?

    flash[:alert] = "Vous avez déjà un accès premium actif."
    redirect_to membres_accespremium_path
  end
end

app/helpers/users_pages_helper.rb
module UsersPagesHelper
end

app/views/users_pages/essays.html.erb
<% content_for :page_title, 'Mes corrigés' %>
<% content_for :h1_title, 'Mes corrigés' %>

<div class="content-user">
  <h1><%= yield (:h1_title) %></h1>

  <p>
    Pour visualiser, modifier ou publier vos corrigés, cliquez sur le titre du sujet.<br />
    Pour mettre en ligne votre corrigé, il faut qu'il ait été soumis à publication puis validé.
  </p>

  <h2 class="mt-4">Mes corrigés en brouillon/en attente de validation</h2>

  <% if @not_published_essays.present? %>
    <table class="standard">
      <thead>
        <tr>
          <td>Sujet</td>
          <td>Matière</td>
          <td>Type</td>
          <td>Catégorie</td>
          <td>Etat</td>
        </tr>
      </thead>
      <tbody>
      <% @not_published_essays.each do |essay_content| %>
        <tr>
          <td class="w-3/5 break-all">
            <%= link_to(essay_content.topic.title, essay_content) %>
          </td>
          <td><%= t(essay_content.essay.topic.category.group.subject).capitalize %></td>
          <td><%= essay_content.essay.topic.category.group.exercice_type.capitalize %></td>
          <td><%= essay_content.essay.topic.category.name %></td>
          <td><%= t(essay_content.essay.status).capitalize %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Vous n'avez pas de corrigé en brouillon/en attente de validation.</p>
  <% end %>

  <h2 class="mt-4">Mes corrigés en ligne</h2>

  <% if @published_essays.present? %>
    <table class="standard">
      <thead>
        <tr>
          <td>Sujet</td>
          <td>Matière</td>
          <td>Type</td>
          <td>Catégorie</td>
        </tr>
      </thead>
      <tbody>
      <% @published_essays.each do |essay_content| %>
        <tr>
          <td class="w-3/5 break-all">
            <%= link_to(essay_content.topic.title, essay_content) %>
          </td>
          <td><%= t(essay_content.essay.topic.category.group.subject).capitalize %></td>
          <td><%= essay_content.essay.topic.category.group.exercice_type.capitalize %></td>
          <td><%= essay_content.essay.topic.category.name %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Vous n'avez pas encore de corrigé publié.</p>
  <% end %>
</div>

app/views/users_pages/home.html.erb
<% content_for :page_title, 'Accueil membre' %>
<% content_for :h1_title, 'Accueil membre' %>
<h1><%= yield (:h1_title) %></h1>

<div class="content-two-columns">
  <div>
    <% if current_user.eleve? %>
      <h2 class=mt-4">Mon accès premium</h2>

      <p>
        <% if current_user.premium_accesses.empty? %>
          Vous n'avez pas d'accès premium.
        <% elsif current_user.active_premium? %>
          Vous avez actuellement un accès premium actif
          (<%= current_user.active_premium_access.stripe? ? "date de renouvellement: " : "date d'expiration: " %>
          <%= current_user.active_premium_access.expire_at.strftime('%d/%m/%Y') %>).
        <% else %>
          Votre dernier accès premium n'est plus actif, il s'est terminé le
          <%= current_user.premium_accesses.order(expire_at: :desc).first.expire_at.strftime("%d/%m/%Y") %>.
        <% end %>
      </p>

      <p>
        <% unless current_user.active_recurring_premium? %>
          <%= link_to('Ajouter un accès premium payant', membres_premiumabonnement_path) %><br />
        <% end %>
        <%= link_to('Voir mes accès premium', membres_accespremium_path) %>
      </p>

    <% end %>

    <% unless current_user.admin? %>
      <h2 class="mt-4">Mes corrigés</h2>

      <p>
        <%= link_to('Ajouter un corrigé', new_essay_contents_internal_path) %><br />
        <%= link_to('Consulter mes corrigés', membres_corriges_path) %>
      </p>
    <% end %>

    <h2 class="mt-4">Mes infos membres</h2>

    <p>
      <%= link_to('Modifier mes infos membres', edit_user_registration_path) %>
    </p>

    <% if current_user.admin? %>
      <h2 class="mt-4">Admin</h2>

      <p>
        <% unless @number_of_pending_essays.zero? %>
          <%= link_to('Corrigés en attente', admin_corriges_path) %>
           (<%= @number_of_pending_essays %>)<br />
        <% end %>
        <%= link_to('Corrigés externes à surveiller', admin_corriges_externes_path) %><br />
        <% unless @number_of_essays_without_proper_plan.zero? %>
          <%= link_to('Plans non conformes', admin_plans_path) %>
           (<%= @number_of_essays_without_proper_plan %>)<br />
        <% end %>
      </p>

      <p>
        <% unless @number_of_topics_without_audios.zero? %>
          <%= link_to('Sujets sans audio', admin_audios_path) %>
           (<%= @number_of_topics_without_audios %>)<br />
        <% end %>
        <% unless @number_of_topics_with_long_titles.zero? %>
          <%= link_to('Titre trop longs', admin_titres_path) %>
           (<%= @number_of_topics_with_long_titles %>)<br />
        <% end %>
        <% unless @number_of_orphan_topics.zero? %>
          <%= link_to('Sujets orphelins', admin_sujets_path) %>
           (<%= @number_of_orphan_topics %>)<br />
        <% end %>
        <%= link_to('Ajouter un sujet', new_topic_path) %><br />
      </p>

      <p>
        <% unless @number_of_categories_missing_info.zero? %>
          <%= link_to('Catégories incomplètes', admin_categories_incompletes_path) %>
           (<%= @number_of_categories_missing_info %>)<br />
        <% end %>
        <% unless @number_of_categories_needing_links.zero? %>
          <%= link_to('Catégories manquant de liens associés', admin_influences_path) %>
           (<%= @number_of_categories_needing_links %>)<br />
        <% end %>
        <% unless @number_of_orphan_categories.zero? %>
          <%= link_to('Catégories orphelines sans avatar', admin_categories_orphelines_path) %>
           (<%= @number_of_orphan_categories %>)<br />
        <% end %>
      </p>

      <p>
        <%= link_to('Liste des professeurs', admin_professeurs_path) %><br />
        <%= link_to('Statistiques', admin_statistiques_path) %><br />
      </p>
    <% end %>
  </div>
  <div class="content-two-columns-right">
    Vous êtes connecté en tant que <span class="font-bold"><%= current_user.username %></span>
    <p class="mt-4"><%= button_to 'Se déconnecter', destroy_user_session_path, method: :delete, data: { turbo: false }, class: "button button-blue" %></p>

    <p>
      Vous avez actuellement comme statut membre: <span class="font-bold"><%= t(current_user.level) %></span>.
    </p>
  </div>
</div>

app/views/users_pages/premium_accesses.html.erb
<% content_for :page_title, 'Mes accès premium' %>
<% content_for :h1_title, 'Mes accès premium' %>

<div class="content-user">
  <h1><%= yield (:h1_title) %></h1>

  <p>
   Vous trouverez ci-dessous l'ensemble de vos accès premium présents ou passées, payants ou offerts suite à la publication d'un corrigé.
  </p>
  <p>Vous pouvez depuis cette page:</p>
  <ul>
    <li class="list-inside list-square">annuler le renouvellement d'un abonnement (qui restera alors actif jusqu'à la date de renouvellement)</li>
    <li class="list-inside list-square">activer un accès premium offert provisionné mais non encore activé (du fait de l'existence d'un abonnement actif)</li>
  </ul>

  <h2 class="mt-4">Mon accès premium actif</h2>
  <% if @active_premium_access.present? %>
    <table class="standard">
      <thead>
        <tr>
          <td>id</td>
          <td>Date d'activation</td>
          <td><%= @active_premium_access.stripe? && @active_premium_access.cancelable? ? "Date de renouvellement":"Date d'expiration" %></td>
          <td class="w-1/4">Type</td>
          <td>Action</td>
        </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @active_premium_access.id %></td>
        <td><%= @active_premium_access.activate_at.strftime('%d/%m/%Y') %></td>
        <td><%= @active_premium_access.expire_at.strftime('%d/%m/%Y') %></td>
        <td><%= t("premium_access_description.#{@active_premium_access.provider}") %></td>
        <td>
          <% if @active_premium_access.cancelable? %>
            <%= link_to('Annuler', { controller: 'premium_accesses', action: 'cancel', id: @active_premium_access.id }, data: { turbo_method: :put }) %>
          <% else %>
            -
          <% end %>
        </td>
      </tr>
      </tbody>
    </table>
  <% else %>
    <p>Vous n'avez pas d'accès premium actif. Pour obtenir un accès premium, <%= link_to('proposez un corrigé', new_essay_contents_internal_path) %> ou <%= link_to('ajoutez un accès premium payant', membres_premiumabonnement_path) %>.
    </ul>
  <% end %>

  <h2 class="mt-4">Mes autres accès premium</h2>
  <% if @other_premium_accesses.present? %>
    <table class="standard">
      <thead>
        <tr>
          <td>id</td>
          <td>Date d'activation</td>
          <td>Date d'expiration</td>
          <td class="w-1/4">Type</td>
          <td>Action</td>
        </tr>
      </thead>
      <tbody>
      <% @other_premium_accesses.each do |premium_access| %>
        <tr>
          <td><%= premium_access.id %></td>
          <td><%= premium_access.activate_at.strftime('%d/%m/%Y') if premium_access.activate_at %></td>
          <td><%= premium_access.expire_at.strftime('%d/%m/%Y') if premium_access.expire_at %></td>
          <td><%= t("premium_access_description.#{premium_access.provider}") %></td>
          <td>
            <% if premium_access.activable? %>
              <%= link_to('Activer', { controller: 'premium_accesses', action: 'activate', id: premium_access.id }, method: :put) %>
            <% else %>
              -
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Vous n'avez pas d'autres accès premium.</p>
  <% end %>
</div>

app/views/users_pages/premium_recurring.html.erb
<% content_for :page_title, "Accès premium par abonnement" %>
<% content_for :h1_title, "Accès premium par abonnement" %>
<% content_for :external_javascript, 'https://js.stripe.com/v3/' %>
<% content_for :additional_javascript, 'stripe_payment' %>
<h1><%= yield (:h1_title) %></h1>

<div class="mt-4 content-two-columns">
  <div>
    <p>
      Accédez à tous les contenus premium, en souscrivant à un abonnement de 5€/mois.
    </p>

    <h2 class="mt-4">Mes informations de paiement</h2>

    <form id="payment-form" class="standard">
        <div>
          <label for="name">Nom du détenteur de la carte bancaire</label>
          <input type="text" id="name" />
        </div>
        <div class="pt-4">
          <span class="font-bold">Informations de la carte bancaire</label>
        </div>
        <div id="card-element">
          <!-- Elements will create input elements here -->
        </div>

        <input type="hidden" id="customer-id" value="<%= @customer_id %>">
        <div class="pt-6 pb-2">
          <input type="submit" id="submit-payment-btn" value="Souscrire">
        </div>
      </form>

  </div>
  <div class="content-two-columns-right">
    Le paiement est sécurisé par la société Stripe. Aucune information bancaire n'est gérée, ni stockée par 20aubac.

    <p class="mt-2 font-bold">
      Abonnement annulable à tout moment
    </p>
    <p>
    Vous pouvez gérer votre abonnement depuis <%= link_to('la page des accès premium', membres_accespremium_path) %>, et résilier à tout moment si nécessaire. Vous bénéficierez des avantages de l'accès premium jusqu'à la date butoir de renouvellement.
    </p>

    <p class="mt-2 font-bold">
      30 jours d'accès premium offerts
    </p>
    <p>
      Vous pouvez également profiter d'un accès premium offert pendant 30 jours en <%= link_to('soumettant un corrigé', new_essay_contents_internal_path) %>.
    </p>
  </div>
</div>