config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match "/404", as: "not_found", to: "errors_pages#not_found", via: :all
  match "/422", as: "unprocessable_entity", to: "errors_pages#internal_server_error", via: :all
  match "/500", as: "internal_error", to: "errors_pages#internal_server_error", via: :all
  get "/sitemap.xml", to: redirect("https://20aubac.s3.eu-west-3.amazonaws.com/sitemap.xml")

  devise_for :users,
    path: "compte",
    skip: [:passwords],
    path_names: {
      sign_in: "acceder",
      sign_out: "deconnecter",
      sign_up: "creer",
      edit: "editer"
    },
    controllers: {registrations: "registrations"}

  authenticate :user, ->(u) { u.admin? } do
    mount ActiveAnalytics::Engine, at: "analytics" # http://localhost:3000/analytics
  end

  devise_scope :user do
    match "/compte/recuperer" => "devise/passwords#create", :as => :user_password, :via => [:post]
    match "/compte/recuperer" => "devise/passwords#update", :via => %i[put patch]
    get "compte/recuperer", to: "devise/passwords#new", as: :new_user_password
    get "mdp/editer", to: "devise/passwords#edit", as: :edit_user_password
  end

  post "acces-premium/abonnement-stripe", to: "premium_accesses#create_stripe_subscription"
  post "acces-premium/notification-stripe", to: "premium_accesses#webhook_stripe"
  put "acces-premium/:id/annuler", to: "premium_accesses#cancel"
  put "acces-premium/:id/activer", to: "premium_accesses#activate"

  root "static_pages#home"
  get "apropos-presentation", to: "static_pages#about_whatwedo"
  get "apropos-publication", to: "static_pages#about_berewarded"
  get "apropos-premium", to: "static_pages#about_premiumaccess"
  get "apropos-mentions", to: "static_pages#about_legalstatement"
  get "apropos-partenaires", to: "static_pages#about_partners"
  get "plan-site", to: "static_pages#site_plan"

  get "membres-accueil", to: "users_pages#home"
  get "membres-corriges", to: "users_pages#essays"
  get "membres-accespremium", to: "users_pages#premium_accesses"
  get "membres-premiumabonnement", to: "users_pages#premium_recurring"

  get "admin-corriges", to: "admin_pages#essays"
  get "admin-corriges-externes", to: "admin_pages#external_essays"
  get "admin-plans", to: "admin_pages#plans"
  get "admin-audios", to: "admin_pages#audios"
  get "admin-titres", to: "admin_pages#titles"
  get "admin-sujets", to: "admin_pages#topics"
  get "admin-categories-incompletes", to: "admin_pages#categories_missing_info"
  get "admin-influences", to: "admin_pages#influences"
  get "admin-categories-orphelines", to: "admin_pages#orphan_categories"
  get "admin-professeurs", to: "admin_pages#professors"
  get "admin-statistiques", to: "admin_pages#statistics"

  get "corriges-populaires", to: "essays#most_popular"
  get "corriges-recents", to: "essays#recently_updated"

  get "recherche", to: "topics#search"

  namespace :essay_contents, path: "" do
    resources :internals, path: "corriges", except: %i[index] do
      put "publish", on: :member
      put "validate", on: :member
      put "premiumize", on: :member
      put "update_topic", on: :member
    end

    resources :externals, path: "corriges-externes", only: %i[show destroy] do
      put "archive", on: :member
      get "archive-html", on: :member
      get "archive-pdf", on: :member
    end
  end

  namespace :quiz do
    resource :answers, path: "", only: %i[show new create]
  end

  get "categories/karl-popper/sujets", to: redirect("/categories/popper/sujets")
  get "categories/pierre-duhem/sujets", to: redirect("/categories/duhem/sujets")
  get "categories/alain-badiou/sujets", to: redirect("/categories/badiou/sujets")
  get "categories/rousseau/sujets", to: redirect("/categories/rousseau-philo/sujets")
  get "categories/jean-jacques-rousseau/sujets", to: redirect("/categories/rousseau-francais/sujets")
  get "categories/jean-paul-sartre/sujets", to: redirect("/categories/sartre-philo/sujets")
  get "categories/sartre/sujets", to: redirect("/categories/sartre-francais/sujets")
  get "categories/diderot/sujets", to: redirect("/categories/diderot-philo/sujets")
  get "categories/denis-diderot/sujets", to: redirect("/categories/diderot-francais/sujets")
  get "categories/montesquieu/sujets", to: redirect("/categories/montesquieu-philo/sujets")
  get "categories/charles-louis-montesquieu/sujets", to: redirect("/categories/montesquieu-francais/sujets")
  get "categories/russel/sujets", to: redirect("/categories/russell/sujets")

  get "categories/devoir-respect/sujets", to: redirect("/categories/devoir/sujets")
  get "categories/histoire/sujets", to: redirect("/categories/temps/sujets")
  get "categories/justice-droit/sujets", to: redirect("/categories/justice/sujets")
  get "categories/existence-temps/sujets", to: redirect("/categories/temps/sujets")
  get "categories/travail-technique/sujets", to: redirect("/categories/travail/sujets")
  get "categories/societe/sujets", to: redirect("/categories/etat/sujets")
  get "categories/desir/sujets", to: redirect("/categories/bonheur/sujets")
  get "categories/perception/sujets", to: redirect("/categories/conscience/sujets")
  get "categories/autrui/sujets", to: redirect("/categories/conscience/sujets")
  get "categories/theorie-experience/sujets", to: redirect("/categories/science/sujets")
  get "categories/demonstration-logique/sujets", to: redirect("/categories/raison/sujets")
  get "categories/matiere-esprit/sujets", to: redirect("/categories/conscience/sujets")
  get "categories/interpretation/sujets", to: redirect("/categories/conscience/sujets")
  get "categories/philosophie/sujets", to: redirect("/categories/verite/sujets")

  resources :categories, only: %i[index edit update destroy] do
    get "/:matiere-:type", action: :index, on: :collection, as: "params"
    resources :topics, path: "sujets", only: %i[index] do
      get "/:page", action: :index, on: :collection, as: "params"
    end
  end

  resources :topics, path: "sujets", except: %i[index show] do
    get "/:matiere-:type", action: :index_all, on: :collection, as: "params"
  end

  get "francais/commentaires-composes.html", to: redirect("/categories/francais-commentaire")
  get "philo/corriges-dissertation-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "philo/corriges-commentaire-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "francais/commentaires-composes-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "philo/corriges-:type.html", to: redirect("/categories/philosophie-%{type}")
  get "plan-site.html", to: redirect("/plan-site")
  get "apropos-presentation.html", to: redirect("/apropos-presentation")
  get "apropos-contribuez.html", to: redirect("/apropos-publication")
  get "apropos-mentions.html", to: redirect("/apropos-mentions")
  get "recherche.html", to: redirect("/recherche")
  get "compte-creer.html", to: redirect("/compte/creer")
  get "compte-acceder.html", to: redirect("/compte/acceder")
  get "compte-recuperer.html", to: redirect("/compte/recuperer")
  get "aide-cgu.html", to: redirect("/aide-cgu")
  get "francais/commentaires-composes.html", to: redirect("/categories/francais-commentaire")
  get "philo/corriges-dissertation-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "philo/corriges-commentaire-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "francais/commentaires-composes-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "philo/corriges-:type.html", to: redirect("/categories/philosophie-%{type}")
  # TO BE REMOVED: force redirection for legacy urls containing  "-r" in keywords
  get "philo/dissertation-15-dire-autrui-semblable-dire-ressemble-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-16-rapports-autres-necessairement-ordre-conflit-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-53-avoir-raison-contre-autres-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-58-religion-liberte-excluent-elles-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-73-preferer-revolte-resignation-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-79-epictete-entretiens-role-philosophie-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-85-recherche-bonheur-necessairement-immorale-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-88-raison-oppose-toutes-formes-croyance-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-98-usage-raison-garantie-contre-illusion-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-106-accomplir-tous-desirs-bonne-regle-vie-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-124-descartes-lettre-a-elisabeth-rapport-entre-bonheur-chance-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-137-platon-gorgias-457d-458a-il-y-a-plus-grand-avantage-a-etre-refute-que-refuter-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-140-nietzsche-par-dela-bien-mal-role-philosophe-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-148-kant-critique-raison-pratique-loi-morale-liberte-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-157-freud-repression-desirs-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-194-que-veut-dire-se-rendre-maitre-ses-passions-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-204-est-il-raisonnable-aimer-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-208-obeir-est-ce-renoncer-liberte-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-228-religion-nourrit-elle-amour-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-265-travailler-rend-il-libre-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-273-rousseau-contrat-social-passage-etat-nature-etat-civil-r:id.html", to: redirect("/corriges/%{id}")

app/controllers/topics_controller.rb
# frozen_string_literal: true

class TopicsController < ApplicationController
  before_action :authenticate_user!, :require_admin, only: %i[new create edit update destroy]
  before_action :new_topic, only: %i[new create]
  before_action :topic_from_id, only: %i[edit update destroy]
  before_action :essays, only: %i[edit update]
  before_action :groups, only: %i[new create edit update]

  def index
    @category = Category.find_by(slug: params[:category_id])

    if @category
      @topics = Topic.includes(best_essay: :essay_content)
        .displayable
        .where(category: @category)
        .order(:title_arabic_numbers)
        .page(params[:page])
        .per(15)
    else
      return redirect_to(categories_path)
    end

    @display_additional_authors = @topics.count < Topic::DISPLAY_ADDITIONAL_INFO_THRESHOLD && params[:page].blank?
    if @display_additional_authors
      @influencers_or_influencees = @category.influencers_or_influencees
        .order(:sorting_index)
    end
  end

  def search
    @topics = Topic.includes(best_essay: :essay_content)
      .displayable
      .search(params[:q])
      .with_pg_search_rank
      .page(params[:page])
      .per(10)
  end

  def index_all
    @matiere = if Group.subjects.key?(params[:matiere])
      params[:matiere].to_sym
    else
      :philosophie
    end
    @type = if @matiere == :francais
      :commentaire
    elsif Group.exercice_types.key?(params[:type])
      params[:type].to_sym
    else
      :dissertation
    end
    @groups = Group.where(exercice_type: @type, subject: @matiere).where.not(name: Group::NON_ASSIGNED)

    @groups_topics_count = Topic.joins(category: :group)
      .where(group: {exercice_type: Group.exercice_types[@type],
                     subject: Group.subjects[@matiere]})
      .where.not(group: {name: Group::NON_ASSIGNED})
      .where.not(best_essay_id: nil).count

    @categories = Category.preload([topics: [best_essay: :essay_content]])
      .joins([topics: :essays])
      .where(essays: {status: :published})
      .group("categories.id")
      .having("COUNT(essays.id) > 0")
      .order(:sorting_index)
  end

  def new
  end

  def create
    # force the params with the created category to take precedence over the selected category in the form
    author_other = params.dig(:author, :other) if @type == :commentaire
    if author_other.present?
      author_other_category = Category.create_author_other(author_other, @matiere)
      params[:topic][:category_id] = author_other_category.id.to_s
    end
    @topic.assign_attributes(topic_params)
    if @topic.save
      flash[:success] = "Le sujet bien été créé."
      redirect_to(edit_topic_path(@topic))
    else
      render "new", status: 422
    end
  end

  def edit
  end

  def update
    # force the params with the created category to take precedence over the selected category in the form
    author_other = params.dig(:author, :other) if @type == :commentaire
    if author_other.present?
      author_other_category = Category.create_author_other(author_other, @matiere)
      params[:topic][:category_id] = author_other_category.id.to_s
    end
    flash.now[:success] = "Le sujet a bien été mis à jour." if @topic.update(topic_params)
    render "edit", status: 422
  end

  def destroy
    if @topic.essays.empty?
      @topic.destroy
      flash[:success] = "Le sujet a bien été supprimé"
      redirect_to(admin_sujets_path)
    else
      flash.now[:alert] = "Le sujet ne peut être détruit car il a des corrigés associés"
    end
  end

  private

  def topic_params
    params
      .require(:topic)
      .permit(:title, :title_short, :category_id, :studied_text, :book, :part, :themes, :edition, :past_exam, :studied_text_audio)
  end

  def new_topic
    @topic = Topic.new
  end

  def topic_from_id
    @topic = Topic.includes([essays: [essay_content: :user]]).find_by(id: params[:id])
    redirect_to "/404" unless @topic
  end

  def essays
    @essays = @topic.essays
  end

  def groups
    if @topic.new_record?
      @matiere = if Group.subjects.key?(params[:matiere])
        params[:matiere].to_sym
      else
        :philosophie
      end
      @type = if @matiere == :francais
        :commentaire
      elsif Group.exercice_types.key?(params[:type])
        params[:type].to_sym
      else
        :dissertation
      end
    else
      @matiere = @topic.category.group.subject.to_sym
      @type = @topic.category.group.exercice_type.to_sym
    end
    @groups = Group.where(exercice_type: @type, subject: @matiere)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<% content_for :page_title, 'Éditer le sujet' %>
<% content_for :h1_title, 'Éditer le sujet' %>
<h1><%= yield (:h1_title) %></h1>

<% provide(:button_text, 'Sauvegarder les modifications') %>

<h2 class="mt-8">Modifier les informations du sujet</h2>

<%= form_for(@topic, html: { class: 'standard' }) do |f| %>
  <%= render 'shared/form_topic', { form: f, disabled: false } %>
  <div class="mt-4"><%= f.submit yield(:button_text) %></div>
<% end %>


<% unless @essays.empty? %>
  <h2 class="mt-8">Liste des corrigés pour ce sujet</h2>

  <table class="standard">
    <thead>
      <tr>
        <td>id</td>
        <td>Type</td>
        <td>Auteur</td>
        <td>Statut</td>
        <td>MaJ</td>
      </tr>
    </thead>
    <tbody>
      <% @essays.each do |essay| %>
        <tr>
          <td><%= link_to(essay.id, essay.essay_content) %><%= " [Meilleur]" if essay.id === @topic.best_essay_id %></td>
          <td><%= t(essay.essay_content_type).capitalize %></td>
          <td>
            <%= essay.author_name %> (<%= t(essay.author_level) %>)
          </td>
          <td><%= t(essay.status).capitalize %></td>
          <td><%= essay.updated_at.strftime('%d/%m/%Y') %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/topics/index.html.erb
<% content_for :page_title, "#{@category.name} - #{@category.group.exercice_type}s de #{t(@category.group.subject)}" %>
<% content_for :h1_title, "#{@category.name} - #{@category.group.exercice_type}s de #{t(@category.group.subject)}" %>
<% content_for :page_description, "#{@category.name} - #{@category.group.exercice_type}s de #{t(@category.group.subject)}" %>
<% content_for :canonical_url, params[:page] ? params_category_topics_url(@category, page: params[:page]) : category_topics_url(@category) %>
<div class="h-full content">
  <div class="flex flex-col h-full">
    <div class="flex-grow">
      <h1><%= link_to(yield(:h1_title), yield(:canonical_url)) %></h1>

      <div class="pt-4">
      <%# <div class="pt-4 pb-6"> %>
        <%# <%= link_to('Par ordre alphabetique', nil, class: 'button button-gray') %1> %>
        <%# <%= link_to('Par popularité', nil, class: 'button button-transparent') %1> %>
        <%# <%= link_to('Annales uniquement', nil, class: 'button button-transparent') %1> %>
      </div>

      <ul>
        <% @topics.each do |topic| %>
          <li class="list-inside list-square"><%= link_to("#{topic.title}", topic.best_essay.essay_content) %></li>
        <% end %>
      </ul>
    </div>

    <%= paginate @topics %>

    <% if @display_additional_authors %>
      <div>
        <p class="mt-8 font-bold">Nous avons besoins de vous !</p>

        <p>
          Nous manquons de corrigés pour <%= t("category_type.this.#{@category.group.exercice_type}") %>.
          Contribuez en <%= link_to('en proposant un', new_essay_contents_internal_path(type: @category.group.exercice_type, matiere: @category.group.subject)) %>, et gagnez 30 jours d'accès premium !
        </p>
        <% if !@influencers_or_influencees.empty? %>
          <p class="mt-4">
          <span class="font-bold">Découvrez les corrigés <%= t("category_type.of_linked.#{@category.group.exercice_type}") %> : </span>
          <% @influencers_or_influencees.each_with_index do |category, index| %>
            <%= link_to(category.name, category_topics_path(category)) %><%= ', ' unless (index == @influencers_or_influencees.size - 1) %>
          <% end %>
          </p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/index_all.html.erb
<% content_for :page_title, "#{@type.capitalize}s de #{t(@matiere)}, tous les sujets" %>
<% content_for :h1_title, "#{@type.capitalize}s de #{t(@matiere)}, tous les sujets"   %>
<% content_for :page_description, "L'ensemble des sujets de #{@type}s en #{t(@matiere)}"    %>
<% content_for :canonical_url, params_topics_url(matiere: @matiere, type: @type) %>
<div class="content">
  <h1><%= link_to(yield(:h1_title), yield(:canonical_url)) %></h1>

  <p>
    <%= link_to('Vue synthétique', params_categories_path(matiere: @matiere, type: @type)) %>, vue détaillée
  </p>
  <p>
    Choisissez <%= @type == :dissertation ? "le corrigé de dissertation" : "le commentaire" %> souhaité.
    <span class="hidden lg:inline"><br />Vous pouvez rechercher un sujet dans cette page avec votre navigateur en utilisant Ctrl-F ou (CMD-F sur Mac).</span>
  </p>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
    <div>
      <%
        topics_displayed_count = 0
        div_count = 0
      %>
      <% @groups.each do |group| %>
        <h2 class="mt-4"><%= group.name %></h2>
        <% @categories.where(group: group).each do |category| %>
          <%= link_to("#{category.name}", category_topics_path(category), { class: 'font-bold no-underline mt-3 mb-2 inline-block' }) %>
          <ul>
            <% category.topics.each do |topic| %>
              <% if topic.best_essay %>
                <li class="list-inside list-square"><%= link_to("#{topic.title}", topic.best_essay.essay_content) %></li>
              <% end %>
            <% end %>
          </ul>
        <% end %>
        <%
          topics_displayed_count = topics_displayed_count + group.topics.count
          if topics_displayed_count > @groups_topics_count/2 && div_count == 0
            div_count = 1
        %>
            </div><div>
        <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<% content_for :page_title, 'Créer un sujet' %>
<% content_for :h1_title, 'Créer un sujet' %>
<h1><%= yield (:h1_title) %></h1>

<% provide(:button_text, 'Sauvegarder les modifications') %>

<h2 class="mt-8">Création d'un sujet</h2>

<% if @topic.new_record? %>
  <div class="mt-2 mb-1">Type de sujet :</div>
  <%= link_to('Dissertation de philosophie', new_topic_path(type: "dissertation", matiere: "philosophie"),
              { class: "#{@type == :dissertation && @matiere == :philosophie ? 'button button-gray' : 'button button-transparent' }" }) %>
  <%= link_to('Commentaire de philosophie', new_topic_path(type: "commentaire", matiere: "philosophie"),
              { class: "#{@type == :commentaire && @matiere == :philosophie ? 'button button-gray' : 'button button-transparent' }" }) %>
  <%= link_to('Commentaire de français', new_topic_path(type: "commentaire", matiere: "francais"),
              { class: "#{@type == :commentaire && @matiere == :francais ? 'button button-gray' : 'button button-transparent' }" }) %>
<% end %>

<%= form_for(@topic, html: { class: 'standard' }) do |f| %>
  <%= render 'shared/form_topic', { form: f, disabled: false } %>
  <div class="mt-4"><%= f.submit yield(:button_text) %></div>
<% end %>

app/views/topics/search.html.erb
<%
  title =
    if !params[:q] || params[:q].empty?
      'Rechercher un corrigé'
    elsif @topics.empty?
      "Pas de résultats pour: «#{params[:q]}»"
    else
      "Résultats pour: «#{params[:q]}»"
    end
%>
<% content_for :page_title, title %>
<% content_for :h1_title, title %>
<% content_for :page_description, 'Trouvez un corrigé de philosophie ou un commentaire composé de français grâce à notre moteur de recherche dédié.' %>
<% content_for :canonical_url, recherche_url %>
<div class="h-full content">
  <% if !params[:q] || params[:q].empty? || @topics.empty? %>
    <div class="content-centered">
      <h1><%= link_to(yield(:h1_title), yield(:canonical_url)) %></h1>
      <p>
        <% if !params[:q] || params[:q].empty? %>
          Recherchez parmi les corrigés disponibles en saisissant au moins un mot dans la barre de recherche.<br />
        <% elsif @topics.empty? %>
          Vous pouvez essayer d'élargir votre recherche en utilisant des termes moins précis ou plus de termes.<br />
        <% end %>
        Vous pouvez ainsi rechercher un sujet, un auteur, une ou plusieurs notions.
      </p>
      <p>
      Ex:
      <%= link_to('Peut-on se connaître soi-même ?', recherche_path(params: { q: 'Peut-on se connaitre soi-même ?'}), rel: 'nofollow') %>,
      <%= link_to('Rousseau', recherche_path(params: { q: 'Rousseau'}), rel: 'nofollow') %>,
      <%= link_to('liberté Etat', recherche_path(params: { q: 'liberté Etat'}), rel: 'nofollow') %>
      </p>
    </div>
  <% else %>
    <h1><%= link_to(yield(:h1_title), yield(:canonical_url)) %></h1>
    <div class="pt-4">
    <%# <div class="pt-4 pb-6"> %>
      <%# <%= link_to('Tous', nil, class: 'button button-gray') %1> %>
      <%# <%= link_to('Français', nil, class: 'button button-transparent') %1> %>
      <%# <%= link_to('Philosophie', nil, class: 'button button-transparent') %1> %>
      <%# <%= link_to('Annales', nil, class: 'button button-transparent') %1> %>
    </div>
    <ul>
      <% @topics.each do |topic| %>
        <li class="mb-4 list-inside list-square"><%= link_to "#{topic.title}", topic.best_essay.essay_content %></li>
      <% end %>
    </ul>
    <%= paginate @topics %>
  <% end %>
</div>