config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match "/404", as: "not_found", to: "errors_pages#not_found", via: :all
  match "/422", as: "unprocessable_entity", to: "errors_pages#internal_server_error", via: :all
  match "/500", as: "internal_error", to: "errors_pages#internal_server_error", via: :all
  get "/sitemap.xml", to: redirect("https://20aubac.s3.eu-west-3.amazonaws.com/sitemap.xml")

  devise_for :users,
    path: "compte",
    skip: [:passwords],
    path_names: {
      sign_in: "acceder",
      sign_out: "deconnecter",
      sign_up: "creer",
      edit: "editer"
    },
    controllers: {registrations: "registrations"}

  authenticate :user, ->(u) { u.admin? } do
    mount ActiveAnalytics::Engine, at: "analytics" # http://localhost:3000/analytics
  end

  devise_scope :user do
    match "/compte/recuperer" => "devise/passwords#create", :as => :user_password, :via => [:post]
    match "/compte/recuperer" => "devise/passwords#update", :via => %i[put patch]
    get "compte/recuperer", to: "devise/passwords#new", as: :new_user_password
    get "mdp/editer", to: "devise/passwords#edit", as: :edit_user_password
  end

  post "acces-premium/abonnement-stripe", to: "premium_accesses#create_stripe_subscription"
  post "acces-premium/notification-stripe", to: "premium_accesses#webhook_stripe"
  put "acces-premium/:id/annuler", to: "premium_accesses#cancel"
  put "acces-premium/:id/activer", to: "premium_accesses#activate"

  root "static_pages#home"
  get "apropos-presentation", to: "static_pages#about_whatwedo"
  get "apropos-publication", to: "static_pages#about_berewarded"
  get "apropos-premium", to: "static_pages#about_premiumaccess"
  get "apropos-mentions", to: "static_pages#about_legalstatement"
  get "apropos-partenaires", to: "static_pages#about_partners"
  get "plan-site", to: "static_pages#site_plan"

  get "membres-accueil", to: "users_pages#home"
  get "membres-corriges", to: "users_pages#essays"
  get "membres-accespremium", to: "users_pages#premium_accesses"
  get "membres-premiumabonnement", to: "users_pages#premium_recurring"

  get "admin-corriges", to: "admin_pages#essays"
  get "admin-corriges-externes", to: "admin_pages#external_essays"
  get "admin-plans", to: "admin_pages#plans"
  get "admin-audios", to: "admin_pages#audios"
  get "admin-titres", to: "admin_pages#titles"
  get "admin-sujets", to: "admin_pages#topics"
  get "admin-categories-incompletes", to: "admin_pages#categories_missing_info"
  get "admin-influences", to: "admin_pages#influences"
  get "admin-categories-orphelines", to: "admin_pages#orphan_categories"
  get "admin-professeurs", to: "admin_pages#professors"
  get "admin-statistiques", to: "admin_pages#statistics"

  get "corriges-populaires", to: "essays#most_popular"
  get "corriges-recents", to: "essays#recently_updated"

  get "recherche", to: "topics#search"

  namespace :essay_contents, path: "" do
    resources :internals, path: "corriges", except: %i[index] do
      put "publish", on: :member
      put "validate", on: :member
      put "premiumize", on: :member
      put "update_topic", on: :member
    end

    resources :externals, path: "corriges-externes", only: %i[show destroy] do
      put "archive", on: :member
      get "archive-html", on: :member
      get "archive-pdf", on: :member
    end
  end

  namespace :quiz do
    resource :answers, path: "", only: %i[show new create]
  end

  get "categories/karl-popper/sujets", to: redirect("/categories/popper/sujets")
  get "categories/pierre-duhem/sujets", to: redirect("/categories/duhem/sujets")
  get "categories/alain-badiou/sujets", to: redirect("/categories/badiou/sujets")
  get "categories/rousseau/sujets", to: redirect("/categories/rousseau-philo/sujets")
  get "categories/jean-jacques-rousseau/sujets", to: redirect("/categories/rousseau-francais/sujets")
  get "categories/jean-paul-sartre/sujets", to: redirect("/categories/sartre-philo/sujets")
  get "categories/sartre/sujets", to: redirect("/categories/sartre-francais/sujets")
  get "categories/diderot/sujets", to: redirect("/categories/diderot-philo/sujets")
  get "categories/denis-diderot/sujets", to: redirect("/categories/diderot-francais/sujets")
  get "categories/montesquieu/sujets", to: redirect("/categories/montesquieu-philo/sujets")
  get "categories/charles-louis-montesquieu/sujets", to: redirect("/categories/montesquieu-francais/sujets")
  get "categories/russel/sujets", to: redirect("/categories/russell/sujets")

  get "categories/devoir-respect/sujets", to: redirect("/categories/devoir/sujets")
  get "categories/histoire/sujets", to: redirect("/categories/temps/sujets")
  get "categories/justice-droit/sujets", to: redirect("/categories/justice/sujets")
  get "categories/existence-temps/sujets", to: redirect("/categories/temps/sujets")
  get "categories/travail-technique/sujets", to: redirect("/categories/travail/sujets")
  get "categories/societe/sujets", to: redirect("/categories/etat/sujets")
  get "categories/desir/sujets", to: redirect("/categories/bonheur/sujets")
  get "categories/perception/sujets", to: redirect("/categories/conscience/sujets")
  get "categories/autrui/sujets", to: redirect("/categories/conscience/sujets")
  get "categories/theorie-experience/sujets", to: redirect("/categories/science/sujets")
  get "categories/demonstration-logique/sujets", to: redirect("/categories/raison/sujets")
  get "categories/matiere-esprit/sujets", to: redirect("/categories/conscience/sujets")
  get "categories/interpretation/sujets", to: redirect("/categories/conscience/sujets")
  get "categories/philosophie/sujets", to: redirect("/categories/verite/sujets")

  resources :categories, only: %i[index edit update destroy] do
    get "/:matiere-:type", action: :index, on: :collection, as: "params"
    resources :topics, path: "sujets", only: %i[index] do
      get "/:page", action: :index, on: :collection, as: "params"
    end
  end

  resources :topics, path: "sujets", except: %i[index show] do
    get "/:matiere-:type", action: :index_all, on: :collection, as: "params"
  end

  get "francais/commentaires-composes.html", to: redirect("/categories/francais-commentaire")
  get "philo/corriges-dissertation-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "philo/corriges-commentaire-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "francais/commentaires-composes-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "philo/corriges-:type.html", to: redirect("/categories/philosophie-%{type}")
  get "plan-site.html", to: redirect("/plan-site")
  get "apropos-presentation.html", to: redirect("/apropos-presentation")
  get "apropos-contribuez.html", to: redirect("/apropos-publication")
  get "apropos-mentions.html", to: redirect("/apropos-mentions")
  get "recherche.html", to: redirect("/recherche")
  get "compte-creer.html", to: redirect("/compte/creer")
  get "compte-acceder.html", to: redirect("/compte/acceder")
  get "compte-recuperer.html", to: redirect("/compte/recuperer")
  get "aide-cgu.html", to: redirect("/aide-cgu")
  get "francais/commentaires-composes.html", to: redirect("/categories/francais-commentaire")
  get "philo/corriges-dissertation-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "philo/corriges-commentaire-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "francais/commentaires-composes-:slug.html", to: redirect("/categories/%{slug}/sujets")
  get "philo/corriges-:type.html", to: redirect("/categories/philosophie-%{type}")
  # TO BE REMOVED: force redirection for legacy urls containing  "-r" in keywords
  get "philo/dissertation-15-dire-autrui-semblable-dire-ressemble-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-16-rapports-autres-necessairement-ordre-conflit-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-53-avoir-raison-contre-autres-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-58-religion-liberte-excluent-elles-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-73-preferer-revolte-resignation-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-79-epictete-entretiens-role-philosophie-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-85-recherche-bonheur-necessairement-immorale-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-88-raison-oppose-toutes-formes-croyance-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-98-usage-raison-garantie-contre-illusion-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-106-accomplir-tous-desirs-bonne-regle-vie-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-124-descartes-lettre-a-elisabeth-rapport-entre-bonheur-chance-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-137-platon-gorgias-457d-458a-il-y-a-plus-grand-avantage-a-etre-refute-que-refuter-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-140-nietzsche-par-dela-bien-mal-role-philosophe-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-148-kant-critique-raison-pratique-loi-morale-liberte-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-157-freud-repression-desirs-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-194-que-veut-dire-se-rendre-maitre-ses-passions-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-204-est-il-raisonnable-aimer-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-208-obeir-est-ce-renoncer-liberte-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-228-religion-nourrit-elle-amour-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/dissertation-265-travailler-rend-il-libre-r:id.html", to: redirect("/corriges/%{id}")
  get "philo/commentaire-273-rousseau-contrat-social-passage-etat-nature-etat-civil-r:id.html", to: redirect("/corriges/%{id}")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>
      <%= if content_for?(:page_title)
        yield(:page_title)
      else
        'Dissertations et commentaires corrigés, aide en philosophie et français'
      end %>
    </title>
    <% if content_for?(:page_description) %>
      <meta name="description" content="<%= yield(:page_description) %>" />
    <% end %>
    <% if content_for?(:canonical_url) %>
      <link rel="canonical" href="<%= yield(:canonical_url).chomp("/") %>" />
    <% end %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <% if content_for?(:additional_javascript) %>
      <%= javascript_import_module_tag yield(:additional_javascript) %>
    <% end %>
    <% if content_for?(:external_javascript) %>
      <script src="<%= yield(:external_javascript) %>" data-turbo-track="reload"></script>
    <% end %>
    <% if content_for?(:ld_json) %>
      <script type="application/ld+json">
        <%= yield(:ld_json) %>
      </script>
    <% end %>
  </head>

  <body>
    <div class="min-h-screen grid grid-cols-1 grid-rows-layout">
      <header role="banner" id="header" class="sticky top-0 z-10 items-center p-4 bg-blue-700 col-span-1 grid grid-cols-layout">
        <div class="col-start-2 col-span-1">
          <%= link_to(root_path, aria: { label: "Page d'accueil" }) do %>
            <%= image_tag('logo_20aubac.png', alt: 'logo 20aubac', size: '125x23', class: 'hidden md:block') %>
            <span class="text-4xl text-white icon-home md:hidden"></span>
          <% end %>
        </div>
        <div class="col-start-3 col-span-2">
          <%= form_with(url: "/recherche", method: "get", local: true) do %>
            <%= search_field_tag(:q,
              params[:q],
              placeholder: "Rechercher un sujet, auteur, notion",
              aria: { label: "Rechercher un sujet, un auteur, une notion" },
              class: "appearance-none outline-none focus:outline-none focus:ring-0
                 bg-blue-700 pl-1 w-2/3 md:w-4/6 lg:w-5/6 text-lg text-gray-200
                 focus:text-white hover:text-white
                 border-x-0 border-t-0 border-b-1 border-gray-400
                 focus:border-white hover:border-white placeholder:text-gray-300"
            ) %>
            <%= submit_tag("Ok", class: "appearance-none uppercase font-semibold px-2 md:m-2 bg-blue-800 hover:bg-blue-900 focus:shadow-outline text-gray-400") %>
          <% end %>
        </div>
        <div class="col-start-5 col-span-1 flex justify-end items-center lg:gap-1">
          <div>
            <% if current_user&.active_premium? %>
                <%= button_to(membres_accespremium_path, method: :get, class: 'header-link') do %>
                  <span class="hidden lg:inline">Premium</span> <span class="icon-star-solid"></span>
                <% end %>
            <% elsif !current_user&.professeur? && !current_user&.admin? %>
              <%= button_to(apropos_premium_path, method: :get, class: 'header-link') do %>
                <span class="hidden lg:inline">Premium</span> <span class="icon-star-regular"></span>
              <% end %>
            <% end %>
          </div>
          <div>
            <% if current_user %>
              <%= button_to(membres_accueil_path, method: :get, aria: { label: 'Compte' }, class: 'header-link') do %>
               <span class="hidden lg:inline">Compte</span> <span class="icon-user-solid"></span>
              <% end %>
            <% else %>
              <%= button_to(new_user_session_path, method: :get, aria: { label: 'Compte' }, class: 'header-link') do %>
               <span class="hidden lg:inline">Compte</span> <span class="icon-user-regular"></span>
              <% end %>
            <% end %>
          </div>
        </div>
      </header>
      <div id="progress-bar" class="hidden h-1 fixed top-[73px] z-20 bg-gray-300"></div>
      <nav role="navigation" class="px-4 py-2 bg-blue-800 grid grid-cols-layout">
        <div class="text-right col-start-2 col-span-4">
          <div class="block md:inline">
            <span id="menu-francais" class="text-blue-200">Français:</span>
            <ul aria-labelledby="menu-francais" class="inline">
              <li class="inline ml-1">
                <%= link_to('Commentaires', params_categories_path(type: "commentaire", matiere: "francais"), { class: "text-blue-200" }) %>
              </li>
            </ul>
          </div>
          <div class="block md:inline md:ml-3 mt-0.5 md:mt-0">
            <div id="menu-philosophie" class="inline text-blue-200">
              <span class="hidden md:inline">Philosophie:</span>
              <span class="inline md:hidden">Philo:</span>
            </div>
            <ul aria-labelledby="menu-philosophie" class="inline">
              <li class="inline ml-1">
                <%= link_to('Dissertations', params_categories_path(type: "dissertation", matiere: "philosophie"), { class: "text-blue-200" } ) %>
              </li>
              <li class="inline ml-1">
                <%= link_to('Commentaires', params_categories_path(type: "commentaire", matiere: "philosophie"), { class: "text-blue-200" }) %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="px-4 bg-green-200 grid grid-cols-layout">
        <div class="success col-start-2 col-span-4">
          <div class="<% if notice || flash[:success] %>py-2<% end %>" id="flash-success">
            <%= notice || flash[:success] %>
          </div>
        </div>
      </div>
      <div class="px-4 bg-red-200 grid grid-cols-layout">
        <div class="error col-start-2 col-span-4">
          <div class="<% if alert %>py-2<% end %>" id="flash-error">
            <%= alert %>
          </div>
        </div>
      </div>
      <main role="main" class="bg-white lg:py-4 grid grid-cols-layout">
        <div class="col-start-2 col-span-4">
          <%= content_for?(:content) ? yield(:content) : yield %>
        </div>
      </main>
      <nav role="navigation" class="items-center px-4 py-2 bg-blue-800 grid grid-cols-layout">
        <div class="text-blue-200 break-words col-start-2 col-span-4">
          <%= link_to('Plan du site', plan_site_path) %>
          > <%= link_to('Accueil', root_path) %>
          <% if controller_name == 'static_pages' && action_name != 'home' %>
            > A propos du site: <%= link_to('Présentation', apropos_presentation_path) %>
                                 / <%= link_to('Contribuez', apropos_publication_path) %>
                                 / <%= link_to('Accès premium', apropos_premium_path) %>
                               / <%= link_to('Mentions légales', apropos_mentions_path) %>
                               / <%= link_to('Partenaires', apropos_partenaires_path) %>
          <% elsif controller_name == 'categories' %>
            <% if params[:matiere] == 'philosophie' %>
              > <%= link_to('Dissertations', params_categories_path(matiere: 'philosophie', type: 'dissertation')) %>
              ou <%= link_to('Commentaires', params_categories_path(matiere: 'philosophie', type: 'commentaire')) %> de philosophie
            <% else %>
              > <%= link_to('Commentaires de français', params_categories_path(matiere: 'francais', type: 'commentaire')) %>
            <% end %>
          <% elsif controller_name == 'topics' && action_name == 'index' %>
            <% if @category.group.philosophie? %>
              > <%= link_to('Dissertations', params_categories_path(matiere: 'philosophie', type: 'dissertation')) %>
              ou <%= link_to('Commentaires', params_categories_path(matiere: 'philosophie', type: 'commentaire')) %> de philosophie
            <% else %>
              > <%= link_to('Commentaires de français', params_categories_path(matiere: 'francais', type: 'commentaire')) %>
            <% end %>
            > <%= link_to(@category.name, category_topics_path(@category)) %>
          <% elsif controller_name == 'topics' && action_name == 'index_all' %>
            > Index des sujets:
             <%= link_to('Dissertations de philosophie', params_topics_path(matiere: 'philosophie', type: 'dissertation')) %>,
             <%= link_to('Commentaires de philosophie', params_topics_path(matiere: 'philosophie', type: 'commentaire')) %>,
             <%= link_to('Commentaires de français', params_topics_path(matiere: 'francais', type: 'commentaire')) %>
          <% elsif controller_name == 'topics' && action_name == 'search' %>
            <% if params[:q] && params[:q].present? %>
              > <%= link_to('Recherche', recherche_path) %> pour les termes: «<%= params[:q] %>»
            <% else %>
              > <%= link_to('Rechercher un sujet', recherche_path) %>
            <% end %>
          <% elsif controller_name == 'essays' %>
            > <%= link_to('Corrigés récemment ajoutés ou mis à jour', corriges_recents_path) %> / <%= link_to('Corrigés les plus populaires', corriges_populaires_path) %>
          <% elsif controller_path =~ /^essay_contents\// && action_name == 'show' %>
            <% if @essay_content.topic.category.group.philosophie? %>
              > <%= link_to('Dissertations', params_categories_path(matiere: 'philosophie', type: 'dissertation')) %>
              ou <%= link_to('Commentaires', params_categories_path(matiere: 'philosophie', type: 'commentaire')) %> de philosophie
            <% else %>
              > <%= link_to('Commentaires de français', params_categories_path(matiere: 'francais', type: 'commentaire')) %>
            <% end %>
            > <%= link_to(@essay_content.topic.category.name, category_topics_path(@essay_content.topic.category)) %>
            > <%= link_to(@essay_content.topic.title, @essay_content) %>
          <% elsif controller_path =~ /^essay_contents\// && action_name != 'show' ||
                   controller_name == 'users_pages' ||
                   controller_name == 'admin_pages' ||
                   controller_name == 'registrations' && action_name == 'edit' %>
            > <%= link_to('Accueil membre', membres_accueil_path) %>
          <% end %>
        </div>
      </nav>
      <footer role="contentinfo" class="p-4 text-gray-200 bg-blue-700">
        <div class="grid grid-cols-layout">
          <div class="col-start-2 col-span-4 md:col-start-2 md:col-span-1">
            <p class="font-bold">A propos</p>
            <nav>
              <ul>
                <li><%= link_to('Présentation du site', apropos_presentation_path) %></li>
                <li><%= link_to('Accès premium', apropos_premium_path) %></li>
                <li><%= link_to('Publiez vos corrigés', apropos_publication_path) %></li>
                <li><%= link_to('Mentions légales', apropos_mentions_path) %></li>
                <li><%= link_to('Partenaires', apropos_partenaires_path) %></li>
              </ul>
            </nav>
          </div>
          <div class="col-start-2 col-span-4 md:col-start-3 md:col-span-2">
            <p><strong>Corrigés les plus populaires</strong></p>
            <nav>
              <ul>
                <% @top_five_essays.each do |essay| %>
                  <li><%= link_to(essay.topic.title_short.presence || essay.topic.title, essay.essay_content) %></li>
                <% end %>
              </ul>
            </nav>
          </div>
          <div class="col-start-2 col-span-4 md:col-start-5 md:col-span-1">
            <p><strong>Catégories les plus populaires</strong></p>
            <nav>
              <ul>
                <% @top_five_categories.each do |category| %>
                  <li><%= link_to(category.name, category_topics_path(category)) %></li>
                <% end %>
              </ul>
            </nav>
          </div>
        </div>
        <div class="grid grid-cols-layout">
          <div class="col-start-2 col-span-4">
            <ul class="mt-8">
              <li class="inline mr-2">
                <strong>Découvrir aussi :</strong>
              </li>
              <li class="inline mr-2">
                <%= link_to('Quiz', new_quiz_answers_path) %>
              </li>
              <li class="inline">
                <%= link_to('https://www.simulateur-bac.fr', target: "_blank") do %>
                  Simulateur bac <span class="icon-external-link"></span>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/quiz_answer.html.erb
<% content_for :content do %>
  <div class="content">
    <h1>Quiz</h1>

    <div class="flex flex-col justify-between">
      <fieldset class="border border-gray-400 mt-8 p-6">
        <legend>Votre choix de catégorie</legend>
        <%= turbo_frame_tag "quiz_selects" do %>
          <%= render("quiz/answers/selects", selected_questions: @selected_questions) %>
        <% end %>
      </fieldset>

      <fieldset class="border border-gray-400 mt-8 p-6">
        <legend>Votre question</legend>
        <%= turbo_frame_tag "quiz_question" do %>
          <%= render("quiz/answers/question", question: @answer.question) %>
        <% end %>
        <%= turbo_frame_tag "quiz_answer" do %>
          <%= yield %>
        <% end %>
      </fieldset>

      <fieldset class="border border-gray-400 mt-8 p-6">
        <legend>Vos statistiques</legend>
        <%= turbo_frame_tag "quiz_stats" do %>
          <%= render("quiz/answers/stats", user: current_user) %>
        <% end %>
      </fieldset>
    </div>
  </div>
<% end %>

<%= render template: 'layouts/application' %>